### ISSUE TITLE
LoadWifiList only returns list from previous system wifi scan list

### ISSUE THREAD

**Issue by BillMac4440** [flutternetwork/WiFiFlutter#129]
Running on Android 11.
The list returned is only the last time you went in and scanned from the system.  New access points won't show up until you do that.
It seems it should refresh this list on its own.  Perhaps a call is missing?
I can sort of work around it for now, but it would be great to have it fully working.
I'm testing the embedded device with this app.  Really not enough of a Flutter guru to run down the issue, but happy to test for anybody.

**Comment by BillMac4440** [comment]
If you turn on WiFi in a new area (such as home or work), it seems to get the list correctly, If another access point shows up while you are on a WiFi, the list from the call will not have the new AP until you scan from the system utility.
For example: Say you are on your home network.  You power up the embedded device that needs configured, and it brings up its access point.  You will not see that AP until you scan from the system.  When you scan again from the function call, the new AP is there, you can select it, then all is well.  
This probably goes to the underlying Android code to force a new scan.

**Comment by gabrieletelesca** [comment]
I "solved" this problem by manually performing a scan in native language. Notice that in Android you can perform only 4 scan every two minutes, independently of their frequency.

**Comment by BenoitDuffez** [comment]
@gabrieletelesca how did you do it in native? it could be interesting to add it to the dart API (would work on Android only)

**Comment by gabrieletelesca** [comment]
@BenoitDuffez I followed this tutorial: https://developer.android.com/guide/topics/connectivity/wifi-scan

**Comment by daadu** [comment]
re-written new plugin - currently not released - PR #205 - encourage you to give review, test and give feedback on it.

This issue will be linked to that plugin and will be closed with this PR.
