### ISSUE TITLE
Can we detect ssid is secure or not ??

### ISSUE THREAD

**Issue by sokunsamnang** [flutternetwork/WiFiFlutter#132]
I want to detect ssid security to leading icon wifi. and if wifi are not secure or open, i want to press to connect without pop up dialog to input password.

**Comment by daadu** [comment]
you can call `scan`, to get wifi list - the object has `capabilites` string, if the `String` contains `WPA`, `WEP`, `PSK` in it.

**Comment by sokunsamnang** [comment]
> you can call `scan`, to get wifi list - the object has `capabilites` string, if the `String` contains `WPA`, `WEP`, `PSK` it "needs" password.

Thanks!

**Comment by sokunsamnang** [comment]
Anyway, How can I connect to open Wi-Fi? I used 
                          ```
WiFiForIoTPlugin.connect(
                            wifi.ssid,
                            joinOnce: false,
                            withInternet: true,
                            security: NetworkSecurity.NONE
                          );
```

but seem not working.

**Comment by daadu** [comment]
@sokunsamnang Any log that you can share?

**Comment by sokunsamnang** [comment]
> @sokunsamnang Any log that you can share?

there are not show any log

**Comment by sokunsamnang** [comment]
> Anyway, How can I connect to open Wi-Fi? I used this function, but seem not work.
> 
> ```
> 
> WiFiForIoTPlugin.connect(
>   wifi.ssid,
>   joinOnce: false,
>   withInternet: true,
>   security: NetworkSecurity.NONE
> );
> ```

EDITED: I tried connect to Wi-Fi captive portal.

**Comment by sokunsamnang** [comment]
> @sokunsamnang Any log that you can share?

Did this package work well on sdk 30 android 11 ??

**Comment by daadu** [comment]
`withInternet: true`  internally uses a very different kind of API, which is relatively new.

I haven't personally tested it.

**Comment by sokunsamnang** [comment]
After changed withInternet: from true to false. it worked well on android 7. but on android 11 there no internet access.

**Comment by kostov** [comment]
Sorry if this is wrong place.
We have device with wifi-module (DVR). In Android (11) system WiFi menu I have already registered wifi-network with ssid "DVR-1" and password '12345678'. In my application:
```
await WiFiForIoTPlugin.findAndConnect('DVR-1', password: '12345678', joinOnce: false);
await WiFiForIoTPlugin.forceWifiUsage(true);
```
-- connection established and all works fine. But if we will remove the password (why is it needed?):
```
await WiFiForIoTPlugin.findAndConnect('DVR-1', joinOnce: false);
...
```
-- the app will crash on this call.

**Comment by daadu** [comment]
@kostov Setting ` security: NetworkSecurity.NONE` should solve it.

**Comment by aadi-github** [comment]
> @kostov Setting ` security: NetworkSecurity.NONE` should solve it.
As below findAndConnect don't have security param, we can not use it.
`await WiFiForIoTPlugin.findAndConnect('DVR-1', joinOnce: false);`

As @kostov mentioned that if we are already once registered with network which we can also check by using
`await WiFiForIoTPlugin.isRegisteredWifiNetwork(wifiNetwork.ssid!)`
so there should be a way to connect that network without re-entering password.

I have tried but it fails if 'security: NetworkSecurity.NONE'. is there any new or another api which we can use to reconnect secured network already saved in the device.
Below is the reference code which was executed once `await WiFiForIoTPlugin.isRegisteredWifiNetwork(wifiNetwork.ssid!)` returns true.
`if (isAlreadyRegistered) {
      waitingDialog();
      await WiFiForIoTPlugin.connect(wifiNetwork.ssid!,
              bssid: wifiNetwork.bssid!,
              joinOnce: true,
              security: NetworkSecurity.NONE)
          .then((value) {
        Get.back();
        if (value) {
          _controller.text = '';
          successDialog(wifiNetwork);
        } else {
          failureDialog();
        }
      });
    }`

**Comment by kostov** [comment]
> @kostov Setting ` security: NetworkSecurity.NONE` should solve it.

@daadu
In addition to @aadi-github note, please explain when we should use findAndConnect(..), and when connect(..) method?

**Comment by kostov** [comment]
Both await findAndConnect(..) and await connect(..) method calls on Android 9 just newer return. :(

**Comment by aadi-github** [comment]
> > @kostov Setting ` security: NetworkSecurity.NONE` should solve it.
> > As below findAndConnect don't have security param, we can not use it.
> > `await WiFiForIoTPlugin.findAndConnect('DVR-1', joinOnce: false);`
> 
> As @kostov mentioned that if we are already once registered with network which we can also check by using `await WiFiForIoTPlugin.isRegisteredWifiNetwork(wifiNetwork.ssid!)` so there should be a way to connect that network without re-entering password.
> 
> I have tried but it fails if 'security: NetworkSecurity.NONE'. is there any new or another api which we can use to reconnect secured network already saved in the device. Below is the reference code which was executed once `await WiFiForIoTPlugin.isRegisteredWifiNetwork(wifiNetwork.ssid!)` returns true. `if (isAlreadyRegistered) { waitingDialog(); await WiFiForIoTPlugin.connect(wifiNetwork.ssid!, bssid: wifiNetwork.bssid!, joinOnce: true, security: NetworkSecurity.NONE) .then((value) { Get.back(); if (value) { _controller.text = ''; successDialog(wifiNetwork); } else { failureDialog(); } }); }`

Please let me know what we can do to connect to the saved wifi network again, without password.

**Comment by kostov** [comment]
Found out why it doesn't work on Android 9:  in WifiIotPlugin.connectTo() -> connectToDeprecated() -> registerWifiNetworkDeprecated() method call we can see fail of the moWiFi.updateNetwork(conf) call, it just returns -1 ("Compatibility Note: For applications targeting Build.VERSION_CODES.Q or above, this API will always fail and return -1." -- perhaps because of this, in my build.graddle: targetSdkVersion 31). I don't understand why we need to updateNetwork here, I think we just need to get networkId to put it then in moWiFi.enableNetwork(<here>). I tried to do it and it worked for me.

**Comment by kostov** [comment]
> please explain when we should use findAndConnect(..), and when connect(..) method?

The question no more actual: I've already got into the plugin code, and I saw what the difference is.

Another problem: 
```
await WiFiForIoTPlugin.connect(dvrId, password: password, withInternet: false, security: NetworkSecurity.WPA);
```
-- never returns on google pixel 3 (Android 12). Will try to figure it out in this kamasutra... :)

**Comment by daadu** [comment]
@kostov Sorry, not able to reply you on time. The Wifi APIs and therefore out code is too fragmented because of lot of sutle changes in various Android versions and phones. Therefore, a reform is in plan [#229] - the current plugin is only supported for fixes, etc.

If you find and bug, feel free to file PR against it.

**Comment by kostov** [comment]
I have found something interesting. Suppose our network has ssid 'DVR 1' -- it was received from WiFiForIoTPlugin.loadWifiList() (and all works on Android 11-). Logcat:
```
2022-03-16 12:48:50.598 1800-2152/? D/WifiNetworkFactory: User initiated connect to network: "DVR 1"
< . . . >
2022-03-16 12:48:50.660 1800-2152/? E/WifiConfigManager: Cannot find network with configKey "DVR 1"WPA_PSK-0
2022-03-16 12:48:50.660 1800-2152/? E/WifiNetworkFactory: Network not present in config manager

The first question is: "DVR 1"WPA_PSK-0 -- is it proper configKey?

**Comment by kostov** [comment]
> As @kostov mentioned that if we are already once registered with network which we can also check by using `await WiFiForIoTPlugin.isRegisteredWifiNetwork(wifiNetwork.ssid!)` so there should be a way to connect that network without re-entering password.

In Android API 29+ we need to setup password every time to connect to wifi network, so this question is not to the plugin author.
In Android 28- we need not to setup password to already "configured" (connected earlier) network. I checked it out in own implementation after reading Android documentation.

**Comment by daadu** [comment]
@kostov Regarding Pixel and Android 12 failures - it is being tracked and discussed at #273. Feel free to join the discussion there, closing this issue.
