### ISSUE TITLE
wifi_iot-0.3.3/ios/Classes/WifiIotPlugin.m:2:9: fatal error: 'wifi_iot/wifi_iot-Swift.h' file not found

### ISSUE THREAD

**Issue by iCiki** [flutternetwork/WiFiFlutter#151]
/Users/mac/.pub-cache/hosted/pub.flutter-io.cn/wifi_iot-0.3.3/ios/Classes/WifiIotPlugin.m:2:9: fatal error: 'wifi_iot/wifi_iot-Swift.h' file not found
    #import <wifi_iot/wifi_iot-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by daadu** [comment]
This should be fixed with latest version, therefore closing it.

Feel free to ask to re-open.
