### ISSUE TITLE
Unable to connect to device 

### ISSUE THREAD

**Issue by vishnuvarthann** [flutternetwork/WiFiFlutter#154]
Unabl to connect to device  . i an getteing error message No device found.Make sure  device are turned on  and avilable  to connect   and i am try with Samsung Galaxy S20 5G,

**Comment by vishnuvarthann** [comment]
does this Wififlutter support all the device  api starting from api 26 to api 30 .what arethe restriction is there. like network side 3G OR 5G Network

**Comment by daadu** [comment]
Yes, it supports all Android APIs. post API 29, there are 2 different APIs that the plugin calls based on `withInternet` flag (`WifiNetworkSpecifier` or `WifiNetworkSuggestion`), in `connect` methods, rest caveats are mentioned in README.

**Comment by daadu** [comment]
also if `withInternet` is set to `false`(default), you need to call `forceWifiUsage(true)` and not forget to disable that when you want to use "internet"

**Comment by vishnuvarthann** [comment]
Does it support ios version too  , and in android does it support the below api 29 .

**Comment by daadu** [comment]
Yes it does. Encourgae you to go through README once.

**Comment by daadu** [comment]
Did it work? Should I close the issue?

**Comment by daadu** [comment]
Closing this, because of lack of response.

Feel free to ask to re-open.
