### ISSUE TITLE
Used to connected wifi on the system setting device, can't connect in the app anymore

### ISSUE THREAD

**Issue by sokunsamnang** [flutternetwork/WiFiFlutter#160]
Like I mentioned in the title. when I used to connected wifi on the system setting device, I can't connect wifi in the app anymore unless I go forgot the wifi on the system setting device it'll work in the app.

I would like to make users easier and can connect wifi both on the system setting and in the app.

I testing on Android 7

Log:
D/ConnectivityManager(23921): requestNetwork; CallingUid : 10193, CallingPid : 23921
D/ConnectivityManager(23921): unregisterNetworkCallback; CallingUid : 10193, CallingPid : 23921
E/ConnectivityManager.CallbackHandler(23921): callback not found for RELEASED message

Code:
```
await WiFiForIoTPlugin.connect(
      said, 
      password: _passwordController.text.toString(), 
      joinOnce: false,
      withInternet: false,
     security: NetworkSecurity.WPA,
    );
await WiFiForIoTPlugin.forceWifiUsage(true);
```

**Comment by daadu** [comment]
need to call `WiFiForIoTPlugin.forceWifiUsage(false);` to remove the binding of processs-to-network.

**Comment by sokunsamnang** [comment]
turn `WiFiForIoTPlugin.forceWifiUsage(true);` to `WiFiForIoTPlugin.forceWifiUsage(false);`

or call `WiFiForIoTPlugin.forceWifiUsage(false);` to somewhere else ?

**Comment by daadu** [comment]
I misunderstood your question.

For system wide Wifi you need to use `withInternet: true`.

**Comment by daadu** [comment]
did it work? Should I close the issue?

**Comment by daadu** [comment]
Closing this, because of lack of response.

Feel free to ask to re-open.
