### ISSUE TITLE
Unable to programmatically connect

### ISSUE THREAD

**Issue by chmoore889** [flutternetwork/WiFiFlutter#164]
I'm unable to use the latest version of this package to connect to a WiFi network on Android. Every time I use it I get the message "Something came up. The application has cancelled the request to choose a device." after the popup just loads for 30 seconds.

The `CHANGE_WIFI_STATE` permission is in my main `AndroidManifest.xml` manifest. The code below uses the `connect` method, but I've also tried with `findAndConnect` with the same result.

This is with the latest stable stable Flutter 2.2.3. This test is being done with a moto g(7) power running Android 10.

Minimal example to reproduce:
```dart
import 'package:flutter/material.dart';
import 'package:wifi_iot/wifi_iot.dart';

Future<void> main() async {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp();

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  Future<dynamic> attemptWifi() async {
    await Future(() async {
      return await WiFiForIoTPlugin.connect(
        'ssid',
        password: 'password',
        security: NetworkSecurity.WPA,
      );
    }).timeout(const Duration(seconds: 60), onTimeout: () {
      // Handle auto wifi connection failure
      print('Wifi Connection Timeout');
      return false;
    });
  }

  @override
  void initState() {
    super.initState();
    attemptWifi();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Controller',
      routes: <String, WidgetBuilder>{
        '/': (BuildContext context) => const Scaffold(
              body: Center(
                child: CircularProgressIndicator.adaptive(),
              ),
            ),
      },
      initialRoute: '/',
    );
  }
}
```

**Comment by akarapontdev1996** [comment]
+1

**Comment by daadu** [comment]
The popup timeout is not in our control, it is set by Android.

Do you have any issue if user accepts the connection?

**Comment by chmoore889** [comment]
@daadu It's not possible to accept the connection as the popup shows the loading indicator until it times out. I know that this issue was introduced at some point after the null-safety migration in `0.3.0`.

**Comment by daadu** [comment]
@chmoore889 Any hints in logs? Can you paste it here?

**Comment by chmoore889** [comment]
@daadu Only log was "Something came up. The application has cancelled the request to choose a device." after the timeout. The last time I did testing was a couple months ago so this issue may not be present in the latest version. I'll update here if I try again.

**Comment by math045b** [comment]
Any progression, or suggestions on what to do when running into the same issue of timing out getting the "Something came up. The application has cancelled the request to choose a device." message?

**Comment by daadu** [comment]
I faced this issue when obfuscating dart code - which is fixed in v0.3.11.

Other than that, this issue mainly comes when phone is not able to "find" the network asked for (could be wrongly configured by plugin - wrong ssid, password, security type, etc).

**Comment by daadu** [comment]
Can you make sure you see the network in scanned list in wifi settings?

**Comment by chmoore889** [comment]
@daadu When I was having issues I made sure that I was able to see the network I was trying to connect to in my settings. I haven't been able to try any newer versions to see if the issue was fixed, but I was not obfuscating my code then.

**Comment by daadu** [comment]
@chmoore889 Why close, did you solved the issue? Can you share what was the issue?

**Comment by chmoore889** [comment]
The issue is solved. I opened this several months ago and the issue seems to have been solved in a release since then.
