### ISSUE TITLE
Crash on `await WiFiForIoTPlugin.getSSID()` on Android

### ISSUE THREAD

**Issue by kvedala** [flutternetwork/WiFiFlutter#225]
Until and including `v0.3.12`, the command `await WiFiForIoTPlugin.getSSID()` returned the expected response. However, with the new version `v0.3.13`, the following exception report is thrown and the application crashes. 
```
E/AndroidRuntime( 2331): java.lang.NullPointerException
E/AndroidRuntime( 2331): 	at com.android.wifi.x.com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:137)
E/AndroidRuntime( 2331): 	at android.net.wifi.WifiNetworkSpecifier$Builder.setSsid(WifiNetworkSpecifier.java:135)
E/AndroidRuntime( 2331): 	at com.alternadom.wifiiot.WifiIotPlugin.connectTo(WifiIotPlugin.java:1250)
E/AndroidRuntime( 2331): 	at com.alternadom.wifiiot.WifiIotPlugin.access$200(WifiIotPlugin.java:50)
E/AndroidRuntime( 2331): 	at com.alternadom.wifiiot.WifiIotPlugin$7.run(WifiIotPlugin.java:955)
```

**Comment by daadu** [comment]
@kvedala The logs you posted, does not indicate any issue with `getSSID`, but there could be issue with `connect` method. Do you use it too?

**Comment by daadu** [comment]
Looks like you are passing `nul` in `ssid` argument of your connect/findAndConnect/registerWifi method.

**Comment by daadu** [comment]
@kvedala I am unable to reproduce the bug, did you find anything?

**Comment by daadu** [comment]
Closing this because of lack of response.

Feel free to request re-opening.
