### ISSUE TITLE
Connection Issue.

### ISSUE THREAD

**Issue by sitakanta136** [flutternetwork/WiFiFlutter#236]
App Try to connect wifi using SSID, password  => Connected 
but when I connect that wifi using ssh using port 22 => Timeout Exception 

Why is the dialog showing a Temporary connection?
Error: connection_failure
      Error Message: java.net.ConnectException: failed to connect to /192.168.0.1 (port 22) from /:: (port 40620): connect failed: ETIMEDOUT (Connection timed out)

**Comment by sitakanta136** [comment]
var isConnected = await WiFiForIoTPlugin.connect(resultssid,
          password: wifiPassword,
          joinOnce: false,
          security: NetworkSecurity.WPA);

      if (isConnected) {
        developer.log('Connected Sucessfully');
        navigateToDisplayWifiLogs();
      } else {
        developer.log('Not Connected ');
      } */

**Comment by daadu** [comment]
Not tried SSH myself, but you should `forceWifiUsage(true)` and disbale again before communicating with clients on the network.

**Comment by qhu91it** [comment]
My case connect to wifi and ping to tcp socket
With setting `withInternet: false`, set `forceWifiUsage(true)` on phone poco f2 pro (xiaomi) it work well but on samsung m32 can not ping to tcp socket (can connect wifi but no internet access), other samsung device also same.

**Comment by daadu** [comment]
@qhu91it  did you add `android:usesCleartextTraffic="true"` as `<application>`  attribute in Mainfest, maybe that could be the issue.

**Comment by sitakanta136** [comment]
Hi daadu,
I am using the below logic for manually connected wifi using SSID and password.
await WiFiForIoTPlugin.connect() method returned bool value if connected but if connection failed it return false .

But we don't know the accurate reason for connection failure. it's showing some dialogs and at the same time it returns false also. It should be after dialog close then it returns false.

we want why the connection failed. if we know that we can try it with a different password to connect.
Is that possible? Please help..


var isConnected = await WiFiForIoTPlugin.connect(resultssid,
password: wifiPassword,
joinOnce: false,
security: NetworkSecurity.WPA);

  if (isConnected) {
    developer.log('Connected Sucessfully');
    navigateToDisplayWifiLogs();
  } else {
    developer.log('Not Connected ');
  }

**Comment by sitakanta136** [comment]
![Uploading screenshot-1647428874159.png…]()

**Comment by sitakanta136** [comment]
![screenshot-1647428874159](https://user-images.githubusercontent.com/97751886/158579110-7bd71fa9-0f2e-433a-bc7a-9237ed7b6ed4.png)

**Comment by sitakanta136** [comment]
How to handle this dialog.
