### ISSUE TITLE
AndroidManifest.xml clashes with other packages

### ISSUE THREAD

**Issue by dusalex** [flutternetwork/WiFiFlutter#237]
Describe the bug
When trying to upload to the Google Play store, Apps build with wifi_iot may be rejected because of multiple definitions of e.g. "android.permission.ACCESS_COARSE_LOCATION" or "android.permission.ACCESS_FINE_LOCATION" with different maxSdkVersion.

To Reproduce
Build an App with the plugins flutter_reactive_ble and wifi_iot and try to upload the aab file to the Google Playstore. The file will be rejected, because the abovementioned permissions are defined twice in the merged AndroidManifest.xml, once with and once without maxSdkVersion, giving the reason "Duplicate declarations of permission android.permission.ACCESS_COARSE_LOCATION with different maxSdkVersions"

Expected behavior
Uploading apps build with wifi_iot and other packages to the Play Store should work.

Additional context
To avoid such clashes, the packages should not include the permission settings in their AndroidManifest.xml files but instead instruct the user to set these values in their app-level manifests.

**Comment by daadu** [comment]
Not sure if we can remove the permission from the plugin - to maintain backward compatibility.

I checked the [`AndroidManifest.xml` file of  `flutter_reactive_ble`](https://github.com/PhilipsHue/flutter_reactive_ble/blob/master/packages/reactive_ble_mobile/android/src/main/AndroidManifest.xml), they use `uses-permission-sdk-23` for "Location permissions", while the wifi functionality that require "location permissions" are scan related and `isConnected` - and is required for < v23 (although not sure).

If you use this functions of `wifi_iot` that requires "loc-permisions" - you can remove the permissions mentioned by the "ble" lib:

```xml
<!-- remove the permission mentioned in ble lib -->
<uses-permission-sdk-23
        android:name="android.permission.ACCESS_COARSE_LOCATION"
        android:maxSdkVersion="30"
        tools:node="remove" />
    <uses-permission-sdk-23
        android:name="android.permission.ACCESS_FINE_LOCATION"
        android:maxSdkVersion="30"
        tools:node="remove" />
```

Although not checked myself,  you can check the APK after build you should see only 2 (coarse and fine) permissions - without and `maxSdkVersion or `<uses-permission-sdk-23>`

**Comment by dusalex** [comment]
@daadu: Thanks, I wasn't aware about the
```tools:node="remove"```
fix. I'll give it a try and will report here if it solves the issue (I agree that it should 😉).

**Comment by dusalex** [comment]
@daadu: Thanks, again, I can now confirm that your suggestion works.

In addition to the lines to remove the permissions, it is important to also add the "tools" to the manifest tag at the very top of the AndroidManifest.xml file:

`<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example.exampleapp"
  xmlns:tools="http://schemas.android.com/tools">`
