### ISSUE TITLE
Enabling / Disabling WiFi module

### ISSUE THREAD

**Issue by Saddi993** [flutternetwork/WiFiFlutter#244]
I am trying to connect WiFi module using flutter app. but did not find any solution yet.

**Comment by daadu** [comment]
Please give some example code that you tried.

**Comment by Saddi993** [comment]
actually this plugin does not supporting Enabling / Disabling WiFi module

**Comment by daadu** [comment]
It is deprecated with Android SDK >= 29.

**Comment by Saddi993** [comment]
is there any way to achieve this (Enabling / Disabling WiFi module) is flutter?

**Comment by daadu** [comment]
No.
