### ISSUE TITLE
Probe request timing

### ISSUE THREAD

**Issue by xhl28** [flutternetwork/WiFiFlutter#250]
hello everyone! 
i am using wifi_scan: ^0.1.0+3  library to scan nearby wifi networks and take ssid values.  

but i would like to do this every 500ms. 

i'm using android 11 and i've seen  with Wireshark that probe requests are sent about every 3 seconds. 
is there a way to send them more frequently? 

i'm already in developer mode and i've removed the restrictions regarding wifi. 

this is part of my code: 

 onPressed: () async {
                    while (true != false) {
                      await Future.wait(
                          [_startScan(context),
                           _getScannedResults(context)]);
                    }

**Comment by daadu** [comment]
Scan request are throttled by Android - https://developer.android.com/guide/topics/connectivity/wifi-scan#wifi-scan-throttling.

However you can override it with a "Developer Option" settings on it - but this has to be done manually - not intended to be used in production apps.

**Comment by daadu** [comment]
Closing this. Feel free to request re-opening, if required.
