### ISSUE TITLE
[QUESTION] Does this package supports wpa2 enterprise connection?

### ISSUE THREAD

**Issue by ronaldmaymone** [flutternetwork/WiFiFlutter#263]
Didn't find the reference or on the example  a connection with username and password. Am I missing anything? 
If not, could someone point a implementation maybe I could create a PR. I've been trying to config a enterprise connection on Kotlin but without success until the moment

**Comment by daadu** [comment]
WPA2 enterprise - is not completed supported - personal is supported though - with just passphrase, will have to wait for new plugin planned with #189

**Comment by daadu** [comment]
The current `wifi_iot` plugin is under reform - #229 - it is maintained just for fixes as of now. If you are interested in implementing it, let me know - will give you pointers - need to design APIs first - then implement them. You can check the process of `wifi_scan` (released) at #188

**Comment by daadu** [comment]
Closing this, feel free to ask for re-open.
