### ISSUE TITLE
[wifi_iot] Cannot connect to existing SSID on android < 10 

### ISSUE THREAD

**Issue by lmmfranco** [flutternetwork/WiFiFlutter#275]
Wifi IOT version: 0.3.15+2
Device: Android 9, LG (LM-X420BMW)

When connecting to a new network (or if I manually forget the network beforehand) it does connect as expected. But when trying to connect to a network that is saved, it always silently returns false.

I've tried copying over the plugin code to an empty android project in order to debug this issue.
The problem seems to be around this section:
https://github.com/flutternetwork/WiFiFlutter/blob/14686c0ade82bfcf0c9881d587d9b72cc4bc1a2c/packages/wifi_iot/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java#L1335-L1345

`moWiFi.updateNetwork(conf)` apparently always return `-1`.

In my testing, changing this line to `return wifiConfig.networkId;` fixed the problem for my use case.

Maybe there could be added flag `noUpdate: bool` or something similar to skip updating existing networks?
Or maybe an additional API just to enable existing connections?

**Comment by daadu** [comment]
This has been a known bug - expected behaviour for already registered network is to get connected as new network.

If you can find a general fix for it - feel free to file PR.
