### ISSUE TITLE
[wifi_scan]  Are Can APIs  removed?

### ISSUE THREAD

**Issue by bahamut657** [flutternetwork/WiFiFlutter#293]
It seems that using the latest wifi_scan package (0.3.0) does not provide at least these documented implementations:

- `WiFiScan.instance.canStartScan()`, missing method
- `WiFiScan.instance.canGetScannedResults()`, missing method
- `CanStartScan` , missing Map
- `CanGetScannedResults`, missing Map         
- `Stream<**Result**<List<WiFiAccessPoint>`, is returned from ` WiFiScan.instance.onScannedResultsAvailable.listen(evt=>{})`

Another thing is that `Result object` is never documented. How to use it?

**Comment by daadu** [comment]
They are added back, but not released to pub.dev. Can wait or point to git repo instead.

**Comment by BenjiFarquhar** [comment]
Is  `final canScan = await WiFiScan.instance.canStartScan(askPermissions: true);` supposed to ask the user for permissions in version ^0.4.0+1 from pub.dev?

Just trying to use it for the first time and the await just hangs and doesn't ask the user anything.

**Comment by daadu** [comment]
@BenjiFarquhar Are you asking about iOS?

**Comment by daadu** [comment]
@BenjiFarquhar Can you give more info about the device+OS version you tested on.

I just rechecked on Android 9 Redmi device and seems to work

**Comment by BenjiFarquhar** [comment]
@daadu Yes. It was on iOS, so nothing can be done about it. Cheers.
