### ISSUE TITLE
i am kinda new to flutter . i have a question regarding stream and future values . I saw that the values remain same ,only when i press the startlistening function button , the value changes . So the question is that when i move the device can it get new values ?

### ISSUE THREAD

**Issue by silly-panda69** [flutternetwork/WiFiFlutter#302]

**Comment by daadu** [comment]
`starScan` you mean? scanning is triggered by Android itself automatically - there is no period or method mentioned in docs about how often or when is it done - it can also be triggered by app which is what `startScan` does.
