### ISSUE TITLE
Connection timeout cannot be overridden

### ISSUE THREAD

**Issue by adnreych** [flutternetwork/WiFiFlutter#304]
When connecting to wifi programmatically, if the password is incorrect, a system window appears with a suggestion to enter the password. This is given only 30 seconds, including the connection time. That is, there are only about 15 seconds left to enter the password. This patch allows you to override the default timeout specified in the java code as a constant https://github.com/flutternetwork/WiFiFlutter/blob/4fe564b707b5b1b8bacea0af78bd9cc7c624c8ca/packages/wifi_iot/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java#L1396
[timeout-connection.txt](https://github.com/flutternetwork/WiFiFlutter/files/9439277/timeout-connection.txt)

Format files .patch cannot be attached, so I attach a txt, please convert it to a patch, in case you add a change to the plugin code.

**Comment by adnreych** [comment]
`--- packages/wifi_iot/lib/wifi_iot.dart	(revision 4fe564b707b5b1b8bacea0af78bd9cc7c624c8ca)
+++ packages/wifi_iot/lib/wifi_iot.dart	(revision f434ae343b665dc7fd4eafaecf2c7037f8bbe727)
@@ -329,6 +329,7 @@
     bool joinOnce = true,
     bool withInternet = false,
     bool isHidden = false,
+    int timeoutInSeconds = 30,
   }) async {
     // https://en.wikipedia.org/wiki/Service_set_(802.11_network)
     // According to IEEE Std 802.11, a SSID must be between 0 and 32 bytes
@@ -352,6 +353,7 @@
         "join_once": joinOnce,
         "with_internet": withInternet,
         "is_hidden": isHidden,
+        "timeout_in_seconds": timeoutInSeconds,
         "security": serializeNetworkSecurityMap[security],
       });
     } on MissingPluginException catch (e) {
`

**Comment by daadu** [comment]
This feature has landed on pub.dev with [v0.3.17](https://pub.dev/packages/wifi_iot/versions/0.3.17).
