### ISSUE TITLE
[WIFI_SCAN] WiFiScan.instance.canGetScannedResults Not Supported IOS

### ISSUE THREAD

**Issue by kozec9** [flutternetwork/WiFiFlutter#331]
![Screenshot 2566-03-27 at 16 24 43](https://user-images.githubusercontent.com/77321016/227900383-cda6f7f3-14b0-4312-8011-7dde3d2e290e.png)

Android: Work
IOS: Not Support ??

![Screenshot 2566-03-27 at 16 27 28](https://user-images.githubusercontent.com/77321016/227901107-2dc28dfb-01f6-40dc-9633-e6d1cd06c1c9.png)

**Comment by wcoder** [comment]
Because iOS is not supported:

Ref #343 #363

**Comment by daadu** [comment]
Yes, iOS doesn't have any public API for scan functionality.

@wcoder Thanks for clarifying.

Closing this, feel free to ask to re-open.
