### ISSUE TITLE
Wifi scan issue while using it In IOS

### ISSUE THREAD

**Issue by AbdelrahmanEhab20** [flutternetwork/WiFiFlutter#340]
each time i tried to use it to scan and gave me the results it told me not supported  , that's only in IOS , how to fix this issue and get the same results like android

**Comment by wcoder** [comment]
Because iOS is not supported under the hood, look:

https://github.com/flutternetwork/WiFiFlutter/blob/3610335b081901e7368ed7d0aeb687b65fd262f2/packages/wifi_scan/ios/Classes/SwiftWifiScanPlugin.swift#L21-L33

Ref #363

**Comment by daadu** [comment]
Yes, ios doesn't have any public api for "wifi scanning" functionality. The plugin is implemented, so the user doesn't need to check the platform everytime, they can just rely on `canStartScan()` call.

@wcoder Thanks for clarifying.

Closing this issue, feel free to ask for re-opening.
