### ISSUE TITLE
connect() vs findAndConnect()

### ISSUE THREAD

**Issue by claudeJURA** [flutternetwork/WiFiFlutter#357]
Platform: Android

looking at the source both connect() and findAndConnect() boil down to calling the same function on the native android side, the only difference seems to be that findAndConnect() first checks and request some permissions and then enumerates available wifi networks before connecting.

When would I choose to use which method?

**Comment by daadu** [comment]
Yes, you are right - it basically a convenient  function -  I would suggest using `connect` as it more closer to the actual implementation.

Closing this issue, feel free to ask to re-open if you think so.
