### ISSUE TITLE
Unable to access network

### ISSUE THREAD

**Issue by PRLsir** [flutternetwork/WiFiFlutter#362]
I used a wifi_iot to connect to a hotspot where the Internet is not accessible, but I also want to access the Internet through the network of my mobile card, what should I do?
Is it possible to provide a scheme to switch directly between WiFi and mobile networks without any sense。
iOS

**Comment by daadu** [comment]
In iOS there is no such option, the network route is decided by the OS. For android you can use the  `forceWifiUsage` method to toggle enforce traffic via wifi.

Closing this isssue, feel free to ask for reopening if you feel so.

**Comment by PRLsir** [comment]
Thanks, it seems that the configuration of the hotspot itself can be set to solve the problem
