### ISSUE TITLE
[wifi_scan] startScan() returning false on 4th call.

### ISSUE THREAD

**Issue by Bojan227** [flutternetwork/WiFiFlutter#369]
Future<bool> scanWifiNetworks() async {
    final canScan = await wiFiScan.canStartScan();

    if (canScan != CanStartScan.yes) {
      throw 'Unable to scan';
    }

    return await wiFiScan.startScan();
  }

Calling this method on every 10 seconds will return false on the 4th try.
Any idea why this is the case and why when I wait for 2-3 min then again works as normal?

**Comment by daadu** [comment]
There are various restrictions and throttling applied by Android - https://developer.android.com/develop/connectivity/wifi/wifi-scan#wifi-scan-throttling

Closing this issue. Feel free to ask for re-opening.
