### ISSUE TITLE
Error after upgrading to Flutter 3.24.0 and dart sdk 3.5.0

### ISSUE THREAD

**Issue by Bojan227** [flutternetwork/WiFiFlutter#397]
Hey @daadu 
If i run the app with flutter run --release I'm receiving the following error messages. 

![image](https://github.com/user-attachments/assets/b129ce68-74a6-4891-81f6-853438d8449b)
![image](https://github.com/user-attachments/assets/7b2fa68c-b29c-4c4f-8df5-8a8e2d82714c)
![image](https://github.com/user-attachments/assets/36afcc04-9a78-439d-8a9f-b251f5da1e87)
![image](https://github.com/user-attachments/assets/f6fc98b5-ca17-4650-852c-792e89a37afd)

Flutter doctor 
![image](https://github.com/user-attachments/assets/267711d1-4443-4be3-ac09-fc0058c1ecc5)

**Comment by UnluckyY1** [comment]
Occurs after upgrade flutter to 3.24.

Roll flutter back to 3.22 may solve it.

With latest flutter 3.24, update the compileSdkVersion  to 31 like the commit [here](https://github.com/realth000/isar/commit/6d0186fc548f4a419f1538f5dc5ec1699f79b2d5) will fix this, too:

Additionally, [change it's dependency](https://github.com/flutternetwork/WiFiFlutter/commit/bbb8c4e569bfd90432ed7fb8903c933cc6bff326) and your app's dependency.

Also the built android libs should be saved in android/src/main/jniLibs.

Or use [my fork](https://github.com/UnluckyY1/WiFiFlutter):

```
wifi_scan:
   git:
      url: https://github.com/UnluckyY1/WiFiFlutter.git
      path: packages/wifi_scan
      ref: bbb8c4e
```

**Comment by carlos00027** [comment]
i've the same problem. when I was upgrade flutter sdk to 3.2.4

**Comment by dt-ebermudez** [comment]
I have the same problem. when I was upgrade flutter sdk to 3.2.4... thx.

**Comment by carlos00027** [comment]
@Bojan227  I've a question. can you execute flutter build appbundle and it's work ok ? and flutter build apk throw exception?

**Comment by GHAMDANdev** [comment]
you must "flutter run --release --verbose" for more details

**Comment by JaredHorwitz** [comment]
@daadu same problem for me when building the app for iOS on Mac

**Comment by daadu** [comment]
Thanks for reporting the issue and apologies for delay in responding.

There is a PR filled on https://github.com/flutternetwork/WiFiFlutter/pull/398 - will do the same for `wifi_iot` as well.

**Comment by daadu** [comment]
The fix has landed on pub.dev with:

- `wifi_iot: ^0.3.19+1`
- `wifi_scan: ^0.4.1+1`

@Bojan227  Thank you for reporting the bug, check yourself in the [CONTRIBUTORS.md](https://github.com/flutternetwork/WiFiFlutter/blob/master/CONTRIBUTORS.md) file.
