### ISSUE TITLE
reduce logging amount

### ISSUE THREAD

**Issue by flukejones** [flutternetwork/WiFiFlutter#69]
During debugging my logs are getting quite cluttered with:

```
D/got wifiIotPlugin(23599): result number of SSID: 12
D/got wifiIotPlugin(23599): final result:  ...etc/etc/etc
```

Is there a way to reduce the amount of logging besides forking and manually doing so? When you have a large block returned from the scan, yeah, just too much...

**Comment by daadu** [comment]
No plan on this + stalled issue, closing this.

Feel free to ask to re-open.
