### ISSUE TITLE
Android 10 can't acces to /proc/net/arp: open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by EParisot** [flutternetwork/WiFiFlutter#73]
`java.io.FileNotFoundException: /proc/net/arp: open failed: EACCES (Permission denied)`

I used the example code in addition to mine and called` WiFiForIoTPlugin.setWiFiAPEnabled(true);`

Storage acces is fine, the app displays images stored on it without issue..., I gess /proc isn't on external storage tho...

It may be related to : 

> On devices that run Android 10 or higher, apps cannot access /proc/net, which includes information about a device's network state. Apps that need access to this information, such as VPNs, should use the NetworkStatsManager or ConnectivityManager class.

from [https://developer.android.com/about/versions/10/privacy/changes](url)

**Comment by daadu** [comment]
Closing this as #114 is resolved.
