### ISSUE TITLE
WiFi AP not working

### ISSUE THREAD

**Issue by JICA98** [flutternetwork/WiFiFlutter#74]
I'm getting platform exception on my android device indicating it doesn't support WiFi AP.  I also tried adding permissions to have full access on the network in the AndroidManifest.xml, but still getting the error. 

E/class info.whitebyte.hotspotmanager.WifiApManager(13476): java.lang.reflect.InvocationTargetException
E/class info.whitebyte.hotspotmanager.WifiApManager(13476): 	at java.lang.reflect.Method.invoke(Native Method)
E/class info.whitebyte.hotspotmanager.WifiApManager(13476): 	at info.whitebyte.hotspotmanager.WifiApManager.getWifiApConfiguration(WifiApManager.java:128)

**Comment by shashank3107** [comment]
I am also facing same problem. Did u get any solution?
