### ISSUE TITLE
doesnt work on android versions 8 and above 

### ISSUE THREAD

**Issue by gau187** [flutternetwork/WiFiFlutter#78]
whenver i try to run on android version 8 or above this plugin doesnt work i have given all permissions but still
i get this error
java.lang.NoSuchMethodException: android.net.wifi.WifiManager.setWifiApEnabled [class android.net.wifi.WifiConfiguration, boolean]

**Comment by daadu** [comment]
Fix for this issue is being work on at #88.

Recommend you to test/review it and provide feedback (instruction are in the PR itself). Merging of #88 will close this issue as well.

**Comment by daadu** [comment]
Fix for this issue is being work on at #88.

Recommend you to test/review it and provide feedback (instruction are in the PR itself). Merging of #88 will close this issue as well.

**Comment by trovend** [comment]
works ok in Android 10 but not on Android 9.
Could someone help with the compatible version chart? (android)
